### PR TITLE
Bootstrap 4 alpha

### PR DESCRIPTION
**Pull request by sllewelyn-mdsol**
# Feature

Include bootstrap 4 alpha

http://v4-alpha.getbootstrap.com/

# Screenshot

image

# Tests

rspec spec/
```
Finished in 2.81 seconds (files took 2.08 seconds to load)
19 examples, 0 failures, 1 pending
```

### CODE REVIEW

**Comment by PepperTeasdale** [comment]
I'm noticing this error: 
Uncaught Error: Bootstrap tooltips require Tether (http://github.hubspot.com/tether/)

**Comment by PepperTeasdale** [comment]
Also, sign_in header says "Bernie", not "Bernie BNB" :)

**Comment by sllewelyn-mdsol** [comment]
Woops, my bad :)  Should it be Bernie or Bernie BNB?  I changed it in this PR https://github.com/SandersForPresident/BernieBNB/pull/30/files

**Comment by sllewelyn-mdsol** [comment]
I'm not getting that Bootstrap tether error.  Can you screenshot it?

**Comment by PepperTeasdale** [comment]
Should be "Bernie BNB"

**Comment by PepperTeasdale** [comment]
bootstrap-error

**Pull request closed without merging**
