### PR TITLE
styled hostings/visits pages

### PR DESCRIPTION
**Pull request by parikhshiv**
i've styled the new and edit hostings/visits pages according to the wireframes - I still need to finish styling the visits show page

### CODE REVIEW

**Comment by PepperTeasdale** [comment]
There's a few things we need to fix in addition to the visit show page:
* Center the "Bernie BNB" header on the sign in/ welcome page
* Style the sign out button. I made a note of it on the design room on slack, should be top-right, across
  from the "<< back" button, styled similarly
* Style error message/ notifications flash

**Comment by parikhshiv** [comment]
Ok sure - I'll take care of this soon as I can.

**Comment by PepperTeasdale** [comment]
Thanks! Have you been in touch with Christopher Mulder (@cmuld3r on slack)
today? I think he is going to contribute some styling, too, and he has some
things that can help make your job easier.

On Tue, Dec 29, 2015 at 2:44 PM, Shiv Parikh <notifications@github.com>
wrote:

> Ok sure - I'll take care of this soon as I can.
>
> On Tue, Dec 29, 2015 at 9:46 AM, Justin Schulz <notifications@github.com>
> wrote:
>
> > There's a few things we need to fix in addition to the visit show page:
> >
> > - Center the "Bernie BNB" header on the sign in/ welcome page
> > - Style the sign out button. I made a note of it on the design room on
> > slack, should be top-right, across from the "<< back" button, styled
> > similarly
> > - Style error message/ notifications flash
> >
> > —
> > Reply to this email directly or view it on GitHub
> > <
> https://github.com/SandersForPresident/BernieBNB/pull/22#issuecomment-167842298
> >
> > .
>
> >
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/SandersForPresident/BernieBNB/pull/22#issuecomment-167862494>
> .
>



-- 
Justin Schulz
Web Developer

T: 314-269-6223
E: justin.schulz@gmail.com
http://www.justinschulz.me/

**Comment by cmuld3r** [comment]
Hey @parikhshiv! Not sure where we missed communication about this, but we should have the whole html/css all ready to go for adapting to our needs from the ridewithbernie codebase. the design was basically forked from that project.

ridewithbernie already has some templates - https://github.com/SandersForPresident/RideWithBernie/tree/master/app/views

and we should probably be using these styles from ridewithbernie, if not already - https://github.com/SandersForPresident/RideWithBernie/blob/master/app/assets/stylesheets/application.css.scss

and we should be importing 'berniestrap', if not already - http://coders.forsanders.com/bootstrap/

and ridewithbernie already has some of our pages, like home, instructions, and profile which we could just adapt easily:
https://github.com/SandersForPresident/RideWithBernie/tree/master/app/assets/javascripts/templates

let me know if you have any questions and if you want some help with this

**Comment by parikhshiv** [comment]
hi chris! dang, i didn't realize this was all ready to go! i'll definitely
try to take a look at this tonight, but like I told Justin, I'm on family
vacation for the week, so my time is limited - I could definitely use some
help if you have any time to look at it!

**Comment by PepperTeasdale** [comment]
Worth noting, @cmuld3r, I've also been writing ERB templates, which are not
based on the RWB codebase, don't know how this will affect things. @cody
didn't want to use angular, so we aren't using underscore templates on
this. Of course, we can adapt these to match what we need for Berniestrap,
but I just wrote the minimal HTML to make the forms work with the backend.

On Tue, Dec 29, 2015 at 3:04 PM, Shiv Parikh <notifications@github.com>
wrote:

> hi chris! dang, i didn't realize this was all ready to go! i'll definitely
> try to take a look at this tonight, but like I told Justin, I'm on family
> vacation for the week, so my time is limited - I could definitely use some
> help if you have any time to look at it!
>
> On Tue, Dec 29, 2015 at 11:58 AM, Christopher Mulder <
> notifications@github.com> wrote:
>
> > Hey @parikhshiv <https://github.com/parikhshiv>! Not sure where we
> missed
> > communication about this, but we should have the whole html/css all ready
> > to go for adapting to our needs from the ridewithbernie codebase. the
> > design was basically forked from that project.
> >
> > ridewithbernie already has some templates -
> >
> https://github.com/SandersForPresident/RideWithBernie/tree/master/app/views
> >
> > and we should probably be using these styles from ridewithbernie, if not
> > already -
> >
> https://github.com/SandersForPresident/RideWithBernie/blob/master/app/assets/stylesheets/application.css.scss
> >
> > and we should be importing 'berniestrap', if not already -
> > http://coders.forsanders.com/bootstrap/
> >
> > and ridewithbernie already has some of our pages, like home,
> instructions,
> > and profile which we could just adapt easily:
> >
> >
> https://github.com/SandersForPresident/RideWithBernie/tree/master/app/assets/javascripts/templates
> >
> > let me know if you have any questions and if you want some help with this
> >
> > —
> > Reply to this email directly or view it on GitHub
> > <
> https://github.com/SandersForPresident/BernieBNB/pull/22#issuecomment-167864610
> >
> > .
>
> >
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/SandersForPresident/BernieBNB/pull/22#issuecomment-167865475>
> .
>



-- 
Justin Schulz
Web Developer

T: 314-269-6223
E: justin.schulz@gmail.com
http://www.justinschulz.me/

**Comment by cmuld3r** [comment]
sure i can try to take a look later tonight and figure out how to merge the styling and templates as best i can.

**Comment by cmuld3r** [comment]
@PepperTeasdale can you figure out how to import berniestrap? that may take me a while if we're not already doing it

**Comment by PepperTeasdale** [comment]
I will try. I've not used bootstrap before, so this is a good learning
opportunity for me.

On Tue, Dec 29, 2015 at 3:14 PM, Christopher Mulder <
notifications@github.com> wrote:

> @PepperTeasdale <https://github.com/PepperTeasdale> can you figure out
> how to import berniestrap? that may take me a while if we're not already
> doing it
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/SandersForPresident/BernieBNB/pull/22#issuecomment-167866999>
> .
>



-- 
Justin Schulz
Web Developer

T: 314-269-6223
E: justin.schulz@gmail.com
http://www.justinschulz.me/

**Comment by cmuld3r** [comment]
i was just confused as i don't see anywhere where ridewithbernie was adding in the bootstrap (berniestrap) css. anyways.

https://github.com/SandersForPresident/RideWithBernie/search?utf8=%E2%9C%93&q=bootstraphttps://github.com/SandersForPresident/RideWithBernie/search?utf8=%E2%9C%93&q=bootstrap

**Comment by cmuld3r** [comment]
oh i guess this:
```
 *= require bootstrap
```

**Pull request merged**
